/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './__root'
import { Route as protectedLayoutRouteImport } from './(protected)/_layout'
import { Route as authLogoutRouteImport } from './(auth)/logout'
import { Route as authLoginRouteImport } from './(auth)/login'
import { Route as authForgotPasswordRouteImport } from './(auth)/forgot-password'
import { Route as protectedLeasingContractsIndexRouteImport } from './(protected)/leasing-contracts/index'
import { Route as protectedLeasingContractsCreateRouteImport } from './(protected)/leasing-contracts/create'
import { Route as protectedLeasingContractsLeaseIdRouteImport } from './(protected)/leasing-contracts/$leaseId'
import { Route as protectedNotificationsNotificationsIndexRouteImport } from './(protected)/notifications/notifications.index'

const protectedRouteImport = createFileRoute('/(protected)')()

const protectedRoute = protectedRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedLayoutRoute = protectedLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => protectedRoute,
} as any)
const authLogoutRoute = authLogoutRouteImport.update({
  id: '/(auth)/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedLeasingContractsIndexRoute =
  protectedLeasingContractsIndexRouteImport.update({
    id: '/leasing-contracts/',
    path: '/leasing-contracts/',
    getParentRoute: () => protectedRoute,
  } as any)
const protectedLeasingContractsCreateRoute =
  protectedLeasingContractsCreateRouteImport.update({
    id: '/leasing-contracts/create',
    path: '/leasing-contracts/create',
    getParentRoute: () => protectedRoute,
  } as any)
const protectedLeasingContractsLeaseIdRoute =
  protectedLeasingContractsLeaseIdRouteImport.update({
    id: '/leasing-contracts/$leaseId',
    path: '/leasing-contracts/$leaseId',
    getParentRoute: () => protectedRoute,
  } as any)
const protectedNotificationsNotificationsIndexRoute =
  protectedNotificationsNotificationsIndexRouteImport.update({
    id: '/notifications/notifications/',
    path: '/notifications/notifications/',
    getParentRoute: () => protectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/logout': typeof authLogoutRoute
  '/': typeof protectedLayoutRoute
  '/leasing-contracts/$leaseId': typeof protectedLeasingContractsLeaseIdRoute
  '/leasing-contracts/create': typeof protectedLeasingContractsCreateRoute
  '/leasing-contracts': typeof protectedLeasingContractsIndexRoute
  '/notifications/notifications': typeof protectedNotificationsNotificationsIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/logout': typeof authLogoutRoute
  '/': typeof protectedLayoutRoute
  '/leasing-contracts/$leaseId': typeof protectedLeasingContractsLeaseIdRoute
  '/leasing-contracts/create': typeof protectedLeasingContractsCreateRoute
  '/leasing-contracts': typeof protectedLeasingContractsIndexRoute
  '/notifications/notifications': typeof protectedNotificationsNotificationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/logout': typeof authLogoutRoute
  '/(protected)': typeof protectedRouteWithChildren
  '/(protected)/_layout': typeof protectedLayoutRoute
  '/(protected)/leasing-contracts/$leaseId': typeof protectedLeasingContractsLeaseIdRoute
  '/(protected)/leasing-contracts/create': typeof protectedLeasingContractsCreateRoute
  '/(protected)/leasing-contracts/': typeof protectedLeasingContractsIndexRoute
  '/(protected)/notifications/notifications/': typeof protectedNotificationsNotificationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/'
    | '/leasing-contracts/$leaseId'
    | '/leasing-contracts/create'
    | '/leasing-contracts'
    | '/notifications/notifications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/'
    | '/leasing-contracts/$leaseId'
    | '/leasing-contracts/create'
    | '/leasing-contracts'
    | '/notifications/notifications'
  id:
    | '__root__'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/logout'
    | '/(protected)'
    | '/(protected)/_layout'
    | '/(protected)/leasing-contracts/$leaseId'
    | '/(protected)/leasing-contracts/create'
    | '/(protected)/leasing-contracts/'
    | '/(protected)/notifications/notifications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authLogoutRoute: typeof authLogoutRoute
  protectedRoute: typeof protectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(protected)': {
      id: '/(protected)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_layout': {
      id: '/(protected)/_layout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedLayoutRouteImport
      parentRoute: typeof protectedRoute
    }
    '/(auth)/logout': {
      id: '/(auth)/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof authLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/leasing-contracts/': {
      id: '/(protected)/leasing-contracts/'
      path: '/leasing-contracts'
      fullPath: '/leasing-contracts'
      preLoaderRoute: typeof protectedLeasingContractsIndexRouteImport
      parentRoute: typeof protectedRoute
    }
    '/(protected)/leasing-contracts/create': {
      id: '/(protected)/leasing-contracts/create'
      path: '/leasing-contracts/create'
      fullPath: '/leasing-contracts/create'
      preLoaderRoute: typeof protectedLeasingContractsCreateRouteImport
      parentRoute: typeof protectedRoute
    }
    '/(protected)/leasing-contracts/$leaseId': {
      id: '/(protected)/leasing-contracts/$leaseId'
      path: '/leasing-contracts/$leaseId'
      fullPath: '/leasing-contracts/$leaseId'
      preLoaderRoute: typeof protectedLeasingContractsLeaseIdRouteImport
      parentRoute: typeof protectedRoute
    }
    '/(protected)/notifications/notifications/': {
      id: '/(protected)/notifications/notifications/'
      path: '/notifications/notifications'
      fullPath: '/notifications/notifications'
      preLoaderRoute: typeof protectedNotificationsNotificationsIndexRouteImport
      parentRoute: typeof protectedRoute
    }
  }
}

interface protectedRouteChildren {
  protectedLayoutRoute: typeof protectedLayoutRoute
  protectedLeasingContractsLeaseIdRoute: typeof protectedLeasingContractsLeaseIdRoute
  protectedLeasingContractsCreateRoute: typeof protectedLeasingContractsCreateRoute
  protectedLeasingContractsIndexRoute: typeof protectedLeasingContractsIndexRoute
  protectedNotificationsNotificationsIndexRoute: typeof protectedNotificationsNotificationsIndexRoute
}

const protectedRouteChildren: protectedRouteChildren = {
  protectedLayoutRoute: protectedLayoutRoute,
  protectedLeasingContractsLeaseIdRoute: protectedLeasingContractsLeaseIdRoute,
  protectedLeasingContractsCreateRoute: protectedLeasingContractsCreateRoute,
  protectedLeasingContractsIndexRoute: protectedLeasingContractsIndexRoute,
  protectedNotificationsNotificationsIndexRoute:
    protectedNotificationsNotificationsIndexRoute,
}

const protectedRouteWithChildren = protectedRoute._addFileChildren(
  protectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authLogoutRoute: authLogoutRoute,
  protectedRoute: protectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
